//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public string MaNV { get; set; }
        public int Ngay { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public string Vao { get; set; }
        public string Ra { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
