//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONLUONG
    {
        public string MaNV { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public string BacLuong { get; set; }
        public Nullable<double> HSPhuCap { get; set; }
        public Nullable<double> ThucLinh { get; set; }
    
        public virtual LUONG LUONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
