//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONGLAODONG
    {
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public string LoaiHD { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
